# Generated by Django 3.2.4 on 2021-06-20 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Identification number must be entered in the format: 199999999. Up to 11 digits allowed', regex='\\d{6,10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_identification',
            field=models.CharField(choices=[('CC', 'cedula'), ('TI', 'id_card')], help_text='type of user identification document: CC or TI.', max_length=2),
        ),
    ]
