# Generated by Django 3.2.4 on 2021-06-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210620_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the user have verified its email add', verbose_name='verified'),
        ),
    ]
