# Generated by Django 3.2.4 on 2021-06-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=0, help_text='user weight in float.', verbose_name='user weight'),
        ),
    ]
